# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Julien MAIRE
title: Recherche d'une alternance en informatique
email: julien.maire0622@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links

github_username:  Eriam60
# stackoverflow_username: "00000001"
# dribbble_username: jekyll

# flickr_username: jekyll
#linkedin_username: Julien
# xing_username: jekyll

# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: À propos de moi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Bonjour, je m'appelle Julien. Après une licence 2 en math/info, je me réoriente vers un <mark>bts SIO option SLAM</mark>. Déterminé, sérieux, autonome et conscient du travail qui m'attend, je suis très motivé à rentrer dans le monde du travail

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Depenses
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Création d’un site de gestion de budget et visualisation graphique des données
        description: |
          Application web qui permet de visualiser et agréger les dépenses hebdomadaires, mensuels et annuels de l'utilisateur.

      

      - layout: top-middle
        title: parc d'attraction
        quote: >
         Création d'un site de gestion d'un parc d'attraction fictif et de sa base de données
        description: | 
          Site web regroupant les différentes attractions, les différents commerces et les différents employés d'un parc d'attraction fictif.



  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SDIS60
        sub_title: Jeunes Sapeurs pompiers
        caption: 2015 - 2019
        quote: > 
          Jeunes sapeurs pompiers
        description: |

        # link_text: boringcompany.com
        sub_title: Sapeur pompier volontaire
        caption: 2019 - 2021
        quote: >
          sapeur pompier volontaire
        description: | # this will include new lines to allow paragraphs
            Pendant 2 années en caserne j'ai pu approfondir mes connaissances et mes formations de jeunes sapeurs pompiers

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Université de Picardie Jules Verne
        caption: 2020 - 2025
        sub_title: licence 2 informatique
        
        description: | # this will include new lines to allow paragraphs
          Apprentissage de plusieurs langages informatique et réalisation de plusieurs projets individuels et projets de groupes. Les différents travaux à réaliser m'ont permis d'acquérir une autonomie dans mon travail ainsi qu'une capacité à travailler engroupe.

  - title: À propos de moi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Voici quelques sujets pour mieux me connaître :
      - jeux vidéos
      - tennis
      - échecs
      - jeux de cartes



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
